SECRET_KEY = ""

PATH_LOG_ERROR_ENABLE = 1
PATH_LOG_ERROR_FILE = "log_error.txt"
MAX_SIZE_LOG_FILE = 1000000

PATH_BERKAS = ""
URL_API_NLP_SAVE_ARTICLE = ""
URL_API_NLP_CHECK = ""
URL_API_NLP_TOPIC = ""
X_API_KEY = ""
URL_API_ARTICLE_KOMINFO = ""
URL_API_CATEGORY_KOMINFO = ""
URL_API_ARTICLE_HOAX_CATEGORY_KOMINFO = ""
X_API_KEY_KOMINFO = ""

APIFY_TOKEN = ""
X_BEARER_TOKEN = ""
MAX_RESULTS = 10